# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::ActionMenu::Heading`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::ActionMenu::Heading`.


class Primer::Alpha::ActionMenu::Heading
  sig { void }
  def initialize; end
end
