# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::Dropdown::Menu::Item`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::Dropdown::Menu::Item`.


class Primer::Alpha::Dropdown::Menu::Item
  sig { void }
  def initialize; end
end
