# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::AutoComplete::Item`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::AutoComplete::Item`.


class Primer::Alpha::AutoComplete::Item
  sig { params(selected: T::Boolean, disabled: T::Boolean, system_arguments: T::Hash).void }
  def initialize(selected:, disabled:, **system_arguments); end
end
