# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::Truncate::TruncateText`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::Truncate::TruncateText`.


class Primer::Beta::Truncate::TruncateText
  sig { void }
  def initialize; end
end
