# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::BaseComponent`.
# Please instead update this file by running `bin/tapioca dsl Primer::BaseComponent`.


class Primer::BaseComponent
  sig { void }
  def initialize; end
end
