# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Box`.
# Please instead update this file by running `bin/tapioca dsl Primer::Box`.


class Primer::Box
  sig { params(system_arguments: T::Hash).void }
  def initialize(**system_arguments); end
end
