# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Component`.
# Please instead update this file by running `bin/tapioca dsl Primer::Component`.


class Primer::Component
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule

  sig { void }
  def initialize; end
end
