# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::ConditionalWrapper`.
# Please instead update this file by running `bin/tapioca dsl Primer::ConditionalWrapper`.


class Primer::ConditionalWrapper
  sig { params(base_component_arguments: T::Hash).void }
  def initialize(**base_component_arguments); end
end
