# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Content`.
# Please instead update this file by running `bin/tapioca dsl Primer::Content`.


class Primer::Content
  sig { void }
  def initialize; end
end
