# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::IconButton`.
# Please instead update this file by running `bin/tapioca dsl Primer::IconButton`.


class Primer::IconButton
  sig { params(scheme: Symbol, box: T::Boolean, tooltip_direction: Symbol, system_arguments: T::Hash).void }
  def initialize(scheme:, box:, tooltip_direction:, **system_arguments); end
end
