# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Tooltip`.
# Please instead update this file by running `bin/tapioca dsl Primer::Tooltip`.


class Primer::Tooltip
  sig do
    params(
      direction: String,
      align: String,
      multiline: T::Boolean,
      no_delay: T::Boolean,
      system_arguments: T::Hash
    ).void
  end
  def initialize(direction:, align:, multiline:, no_delay:, **system_arguments); end
end
