# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Truncate`.
# Please instead update this file by running `bin/tapioca dsl Primer::Truncate`.


class Primer::Truncate
  sig do
    params(
      tag: Symbol,
      inline: T::Boolean,
      expandable: T::Boolean,
      max_width: Integer,
      system_arguments: T::Hash
    ).void
  end
  def initialize(tag:, inline:, expandable:, max_width:, **system_arguments); end
end
