# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::UrlHelpers`.
# Please instead update this file by running `bin/tapioca dsl Primer::UrlHelpers`.


module Primer::UrlHelpers
  extend GeneratedUrlHelpersModule
  extend GeneratedPathHelpersModule
end
