# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::SegmentedControl::Item`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::SegmentedControl::Item`.


class Primer::Alpha::SegmentedControl::Item
  sig { params(selected: T::Boolean, icon: Symbol, hide_labels: Symbol).void }
  def initialize(selected:, icon:, hide_labels:); end
end
