# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::Avatar`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::Avatar`.


class Primer::Beta::Avatar
  sig { params(alt: String, size: Integer, shape: Symbol, href: String, system_arguments: T::Hash).void }
  def initialize(alt:, size:, shape:, href:, **system_arguments); end
end
