# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::ClipboardCopy`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::ClipboardCopy`.


class Primer::Beta::ClipboardCopy
  sig { params(value: String, system_arguments: T::Hash).void }
  def initialize(value:, **system_arguments); end
end
