# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::CloseButton`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::CloseButton`.


class Primer::Beta::CloseButton
  sig { params(type: Symbol, disabled: T::Boolean, system_arguments: T::Hash).void }
  def initialize(type:, disabled:, **system_arguments); end
end
