# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::Heading`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::Heading`.


class Primer::Beta::Heading
  sig { params(system_arguments: T::Hash).void }
  def initialize(**system_arguments); end
end
