# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::Label`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::Label`.


class Primer::Beta::Label
  sig do
    params(
      tag: Symbol,
      scheme: Symbol,
      size: Symbol,
      inline: T::Boolean,
      variant: Symbol,
      system_arguments: T::Hash
    ).void
  end
  def initialize(tag:, scheme:, size:, inline:, variant:, **system_arguments); end
end
