# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::Octicon`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::Octicon`.


class Primer::Beta::Octicon
  sig { params(icon: T.any(Symbol, String), size: Symbol, use_symbol: T::Boolean, system_arguments: T::Hash).void }
  def initialize(icon:, size:, use_symbol:, **system_arguments); end
end
