# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::Spinner`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::Spinner`.


class Primer::Beta::Spinner
  sig { params(size: Symbol, style: String, system_arguments: T::Hash).void }
  def initialize(size:, style:, **system_arguments); end
end
