# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::State`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::State`.


class Primer::Beta::State
  sig { params(scheme: Symbol, tag: Symbol, size: Symbol, system_arguments: T::Hash).void }
  def initialize(scheme:, tag:, size:, **system_arguments); end
end
