# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::Text`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::Text`.


class Primer::Beta::Text
  sig { params(tag: Symbol, system_arguments: T::Hash).void }
  def initialize(tag:, **system_arguments); end
end
