# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::Dialog::Body`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::Dialog::Body`.


class Primer::Alpha::Dialog::Body
  sig { params(system_arguments: T::Hash).void }
  def initialize(**system_arguments); end
end
