# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::Dialog::Footer`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::Dialog::Footer`.


class Primer::Alpha::Dialog::Footer
  sig { params(show_divider: T::Boolean, system_arguments: T::Hash).void }
  def initialize(show_divider:, **system_arguments); end
end
