# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kubectl-rb` gem.
# Please instead update this file by running `bin/tapioca gem kubectl-rb`.


# source://kubectl-rb//lib/kubectl-rb/version.rb#1
module KubectlRb
  class << self
    # source://kubectl-rb//lib/kubectl-rb.rb#2
    def executable; end
  end
end

# source://kubectl-rb//lib/kubectl-rb/version.rb#3
KubectlRb::KUBECTL_VERSION = T.let(T.unsafe(nil), String)

# source://kubectl-rb//lib/kubectl-rb/version.rb#2
KubectlRb::VERSION = T.let(T.unsafe(nil), String)
