# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ms_rest_azure` gem.
# Please instead update this file by running `bin/tapioca gem ms_rest_azure`.


# source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#5
module MsRestAzure; end

# Class which represents an settings for Azure AD authentication.
#
# source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#9
class MsRestAzure::ActiveDirectoryServiceSettings
  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#12
  def authentication_endpoint; end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#12
  def authentication_endpoint=(_arg0); end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#15
  def token_audience; end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#15
  def token_audience=(_arg0); end

  class << self
    # Returns a set of properties required to login into Azure China cloud.
    #
    # @return [ActiveDirectoryServiceSettings] settings required for authentication.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#29
    def get_azure_china_settings; end

    # Returns a set of properties required to login into Azure German Cloud.
    #
    # @return [ActiveDirectoryServiceSettings] settings required for authentication.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#37
    def get_azure_german_settings; end

    # Returns a set of properties required to login into regular Azure cloud.
    #
    # @return [ActiveDirectoryServiceSettings] settings required for authentication.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#21
    def get_azure_settings; end

    # Returns a set of properties required to login into Azure US Government.
    #
    # @return [ActiveDirectoryServiceSettings] settings required for authentication.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#45
    def get_azure_us_government_settings; end

    # Returns a set of properties required to login into Azure Cloud.
    #
    # @param azure_environment [AzureEnvironment] An instance of AzureEnvironment.
    # @return [ActiveDirectoryServiceSettings] settings required for authentication.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/active_directory_service_settings.rb#56
    def get_settings(azure_environment = T.unsafe(nil)); end
  end
end

# Class that provides access to authentication token.
#
# source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#9
class MsRestAzure::ApplicationTokenProvider < ::MsRest::TokenProvider
  # Creates and initialize new instance of the ApplicationTokenProvider class.
  #
  # @param tenant_id [String] tenant id (also known as domain).
  # @param client_id [String] client id.
  # @param client_secret [String] client secret.
  # @param settings [ActiveDirectoryServiceSettings] active directory setting.
  # @return [ApplicationTokenProvider] a new instance of ApplicationTokenProvider
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#55
  def initialize(tenant_id, client_id, client_secret, settings = T.unsafe(nil)); end

  # Returns the string value which needs to be attached
  # to HTTP request header in order to be authorized.
  #
  # @return [String] authentication headers.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#74
  def get_authentication_header; end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#47
  def token; end

  # @return [Time] the date when the current token expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#41
  def token_expires_on; end

  # @return [String] the type of token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#44
  def token_type; end

  private

  # Retrieves a new authentication token.
  #
  # @return [String] new authentication token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#93
  def acquire_token; end

  # @return [String] application id.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#24
  def client_id; end

  # @return [String] application id.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#24
  def client_id=(_arg0); end

  # @return [String] application secret key.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#27
  def client_secret; end

  # @return [String] application secret key.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#27
  def client_secret=(_arg0); end

  # @return [Integer] the amount of time we refresh token before it expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#36
  def expiration_threshold; end

  # @return [ActiveDirectoryServiceSettings] settings.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#18
  def settings; end

  # @return [ActiveDirectoryServiceSettings] settings.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#18
  def settings=(_arg0); end

  # @return [String] tenant id (also known as domain).
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#21
  def tenant_id; end

  # @return [String] tenant id (also known as domain).
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#21
  def tenant_id=(_arg0); end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#30
  def token=(_arg0); end

  # Checks whether token is about to expire.
  #
  # @return [Bool] True if token is about to expire, false otherwise.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#85
  def token_expired; end

  # @return [Time] the date when the current token expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#33
  def token_expires_on=(_arg0); end
end

# source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#15
MsRestAzure::ApplicationTokenProvider::DEFAULT_SCHEME = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#14
MsRestAzure::ApplicationTokenProvider::REQUEST_BODY_PATTERN = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/credentials/application_token_provider.rb#13
MsRestAzure::ApplicationTokenProvider::TOKEN_ACQUIRE_URL = T.let(T.unsafe(nil), String)

# Defines values for AsyncOperationStatus enum.
#
# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#9
class MsRestAzure::AsyncOperationStatus
  # @return [MsRestAzure::CloudErrorData] error information about async operation.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#27
  def error; end

  # @return [MsRestAzure::CloudErrorData] error information about async operation.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#27
  def error=(_arg0); end

  # @return [Integer] delay in seconds which should be used for polling for result of async operation.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#24
  def retry_after; end

  # @return [Integer] delay in seconds which should be used for polling for result of async operation.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#24
  def retry_after=(_arg0); end

  # @return [Stirng] status of polling.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#30
  def status; end

  # @return [Stirng] status of polling.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#30
  def status=(_arg0); end

  class << self
    # Deserializes given hash into AsyncOperationStatus object.
    #
    # @param object [Hash] object to deserialize.
    # @return [AsyncOperationStatus] deserialized object.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#64
    def deserialize_object(object); end

    # Checks if given status is failed one.
    #
    # @param status [String] status to verify
    # @return [Boolean] True if given status is failed one, false otherwise.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#46
    def is_failed_status(status); end

    # Checks if given status is successful one.
    #
    # @param status [String] status to verify
    # @return [Boolean] True if given status is successful one, false otherwise.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#55
    def is_successful_status(status); end

    # Checks if given status is terminal one.
    #
    # @param status [String] status to verify
    # @return [Boolean] True if given status is terminal one, false otherwise.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#37
    def is_terminal_status(status); end
  end
end

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#10
MsRestAzure::AsyncOperationStatus::ACCEPTED = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#17
MsRestAzure::AsyncOperationStatus::ALL_STATUSES = T.let(T.unsafe(nil), Array)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#15
MsRestAzure::AsyncOperationStatus::CANCELED_STATUS = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#21
MsRestAzure::AsyncOperationStatus::DEFAULT_DELAY = T.let(T.unsafe(nil), Integer)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#14
MsRestAzure::AsyncOperationStatus::FAILED_STATUS = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#18
MsRestAzure::AsyncOperationStatus::FAILED_STATUSES = T.let(T.unsafe(nil), Array)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#11
MsRestAzure::AsyncOperationStatus::IN_PROGRESS_STATUS = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#12
MsRestAzure::AsyncOperationStatus::RUNNING = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#13
MsRestAzure::AsyncOperationStatus::SUCCESS_STATUS = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/async_operation_status.rb#19
MsRestAzure::AsyncOperationStatus::TERMINAL_STATUSES = T.let(T.unsafe(nil), Array)

# Class which represents an error with the Azure CLI.
#
# source://ms_rest_azure//lib/ms_rest_azure/azure_cli_error.rb#9
class MsRestAzure::AzureCliError < ::StandardError; end

# Class that provides access to access tokens generated by the azure cli.
#
# source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#11
class MsRestAzure::AzureCliTokenProvider < ::MsRest::TokenProvider
  # Creates and initialize new instance of the AzureCliTokenProvider class.
  #
  # @param settings [ActiveDirectoryServiceSettings] active directory setting.
  # @raise [AzureCliError]
  # @return [AzureCliTokenProvider] a new instance of AzureCliTokenProvider
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#37
  def initialize(settings = T.unsafe(nil)); end

  # Gets an authentication header string using an access token from the Azure cli
  #
  # @param settings [ActiveDirectoryServiceSettings] active directory settings.
  # @return [String] The authenticaiton header string
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#51
  def get_authentication_header; end

  private

  # Acquires a new access token from teh azure CLI
  #
  # @return [String] The access token to the desired resource
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#86
  def acquire_token; end

  # @return [String] the type of token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#15
  def cli_path; end

  # @return [Integer] the amount of time we refresh token before it expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#27
  def expiration_threshold; end

  # Checks if the Azure CLI is installed
  #
  # @return [Boolean] Does the az command exist on the path
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#70
  def locate_azure_cli; end

  # @return [ActiveDirectoryServiceSettings] settings.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#18
  def settings; end

  # @return [ActiveDirectoryServiceSettings] settings.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#18
  def settings=(_arg0); end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#21
  def token; end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#21
  def token=(_arg0); end

  # Checks whether token is about to expire.
  #
  # @return [Bool] True if token is about to expire, false otherwise.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#62
  def token_expired?; end

  # @return [Time] the date when the current token expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#24
  def token_expires_on; end

  # @return [Time] the date when the current token expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#24
  def token_expires_on=(_arg0); end

  # @return [String] the type of token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#30
  def token_type; end
end

# source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#6
module MsRestAzure::AzureEnvironments; end

# source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#105
MsRestAzure::AzureEnvironments::AzureChinaCloud = T.let(T.unsafe(nil), MsRestAzure::AzureEnvironments::AzureEnvironment)

# source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#87
MsRestAzure::AzureEnvironments::AzureCloud = T.let(T.unsafe(nil), MsRestAzure::AzureEnvironments::AzureEnvironment)

# An instance of this class describes an environment in Azure
#
# source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#10
class MsRestAzure::AzureEnvironments::AzureEnvironment
  # @return [AzureEnvironment] a new instance of AzureEnvironment
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#63
  def initialize(options); end

  # @return [String] the Active Directory login endpoint
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#37
  def active_directory_endpoint_url; end

  # @return [String] the Active Directory resource ID
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#46
  def active_directory_graph_api_version; end

  # @return [String] the Active Directory resource ID
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#43
  def active_directory_graph_resource_id; end

  # @return [String] the resource ID to obtain AD tokens for
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#40
  def active_directory_resource_id; end

  # @return [String] the data lake analytics job and catalog service dns suffix
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#58
  def datalake_analytics_catalog_and_job_endpoint_suffix; end

  # @return [String] the data lake store filesystem service dns suffix
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#55
  def datalake_store_filesystem_endpoint_suffix; end

  # @return [String] the template gallery endpoint
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#34
  def gallery_endpoint_url; end

  # @return [String] the KeyVault service dns suffix
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#52
  def key_vault_dns_suffix; end

  # @return [String] the management service endpoint
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#22
  def management_endpoint_url; end

  # @return [String] the Environment name
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#13
  def name; end

  # @return [String] the management portal URL
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#16
  def portal_url; end

  # @return [String] the publish settings file URL
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#19
  def publishing_profile_url; end

  # @return [String] the resource management endpoint
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#25
  def resource_manager_endpoint_url; end

  # @return [String] the sql server management endpoint for mobile commands
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#28
  def sql_management_endpoint_url; end

  # @return [String] the dns suffix for sql servers
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#31
  def sql_server_hostname_suffix; end

  # @return [String] the endpoint suffix for storage accounts
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#49
  def storage_endpoint_suffix; end

  # @return [Boolean] determines whether the authentication endpoint should be validated with Azure AD. Default value is true.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#61
  def validate_authority; end
end

# source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#143
MsRestAzure::AzureEnvironments::AzureGermanCloud = T.let(T.unsafe(nil), MsRestAzure::AzureEnvironments::AzureEnvironment)

# source://ms_rest_azure//lib/ms_rest_azure/azure_environment.rb#124
MsRestAzure::AzureEnvironments::AzureUSGovernment = T.let(T.unsafe(nil), MsRestAzure::AzureEnvironments::AzureEnvironment)

# Class which represents an Azure error.
#
# source://ms_rest_azure//lib/ms_rest_azure/azure_operation_error.rb#9
class MsRestAzure::AzureOperationError < ::MsRest::HttpOperationError
  # Creates and initialize new instance of the AzureOperationError class.
  #
  # @param the [Hash] HTTP request data (uri, body, headers).
  # @param the [Faraday::Response] HTTP response object.
  # @param body [String] the HTTP response body.
  # @param error [String] message.
  # @return [AzureOperationError] a new instance of AzureOperationError
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_error.rb#24
  def initialize(*args); end

  # @return [String] the error code.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_error.rb#15
  def error_code; end

  # @return [String] the error code.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_error.rb#15
  def error_code=(_arg0); end

  # @return [String] the error message.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_error.rb#12
  def error_message; end

  # @return [String] the error message.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_error.rb#12
  def error_message=(_arg0); end
end

# Class which represents the data received and deserialized from Azure service.
#
# source://ms_rest_azure//lib/ms_rest_azure/azure_operation_response.rb#9
class MsRestAzure::AzureOperationResponse < ::MsRest::HttpOperationResponse
  # @return [String] Client Request Id of the request.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_response.rb#18
  def client_request_id; end

  # @return [String] Client Request Id of the request.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_response.rb#18
  def client_request_id=(_arg0); end

  # @return [String] Correlation Id of the request.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_response.rb#15
  def correlation_request_id; end

  # @return [String] Correlation Id of the request.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_response.rb#15
  def correlation_request_id=(_arg0); end

  # @return [String] identificator of the request.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_response.rb#12
  def request_id; end

  # @return [String] identificator of the request.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_operation_response.rb#12
  def request_id=(_arg0); end
end

# Class which represents a point of access to the REST API.
#
# source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#9
class MsRestAzure::AzureServiceClient < ::MsRest::ServiceClient
  # @return [AzureServiceClient] a new instance of AzureServiceClient
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#17
  def initialize(credentials, options = T.unsafe(nil)); end

  # @return [String] api version of the Azure in string format.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#15
  def api_version; end

  # @return [String] api version of the Azure in string format.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#15
  def api_version=(_arg0); end

  # Verifies for unexpected polling status code
  #
  # @param azure_response [MsRestAzure::AzureOperationResponse] response from Azure service.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#122
  def check_for_status_code_failure(azure_response); end

  # Retrieves data by given URL.
  #
  # @param request [MsRest::HttpOperationRequest] the URL.
  # @return [MsRest::HttpOperationResponse] the response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#259
  def get_async_common(request); end

  # Retrieves data by given URL.
  #
  # @param request [MsRest::HttpOperationRequest] the URL.
  # @return [MsRest::HttpOperationResponse] the response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#245
  def get_async_with_async_operation_deserialization(request); end

  # Retrieves data by given URL.
  #
  # @param request [MsRest::HttpOperationRequest] the URL.
  # @param custom_deserialization_block [Proc] function to perform deserialization of the HTTP response.
  # @return [MsRest::HttpOperationResponse] the response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#225
  def get_async_with_custom_deserialization(request, custom_deserialization_block); end

  # Retrieves the result of 'POST','DELETE','PUT' or 'PATCH' operation. Performs polling of required.
  #
  # @param azure_response [MsRestAzure::AzureOperationResponse] response from Azure service.
  # @param custom_deserialization_block [Proc] custom logic for response deserialization.
  # @param final_state_via [MsRestAzure::FinalStateVia] Final State via value
  # @return [MsRest::HttpOperationResponse] the response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#37
  def get_long_running_operation_result(azure_response, custom_deserialization_block, final_state_via = T.unsafe(nil)); end

  # @return [Integer] execution interval for long running operations.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#12
  def long_running_operation_retry_timeout; end

  # @return [Integer] execution interval for long running operations.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#12
  def long_running_operation_retry_timeout=(_arg0); end

  # Updates polling state from Azure async operation header.
  #
  # @param polling_state [MsRestAzure::PollingState] polling state.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#204
  def update_state_from_azure_async_operation_header(request, polling_state); end

  # Updates polling state based on location header for PUT HTTP requests.
  #
  # @param request [MsRest::HttpOperationRequest] The url retrieve data from.
  # @param polling_state [MsRestAzure::PollingState] polling state to update.
  # @param custom_deserialization_block [Proc] custom deserialization method for parsing response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#141
  def update_state_from_get_resource_operation(request, polling_state, custom_deserialization_block); end

  # Updates polling state based on location header for HTTP requests.
  #
  # @param request [MsRest::HttpOperationRequest] The url retrieve data from.
  # @param polling_state [MsRestAzure::PollingState] polling state to update.
  # @param custom_deserialization_block [Proc] custom deserialization method for parsing response.
  # @param final_state_via [MsRestAzure::FinalStateVia] Final State via value
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#173
  def update_state_from_location_header(request, polling_state, custom_deserialization_block, final_state_via = T.unsafe(nil)); end

  private

  # Retrieves a new instance of the AzureOperationResponse class.
  #
  # @param request [MsRest::HttpOperationRequest] the HTTP request object.
  # @param response [Faraday::Response] the HTTP response object.
  # @param body [String] the HTTP response body.
  # @return [MsRestAzure::AzureOperationResponse] the operation response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/azure_service_client.rb#299
  def create_response(request, http_response, body = T.unsafe(nil)); end
end

# Class which represents keeps aux data about Azure invalid response.
#
# source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#9
class MsRestAzure::CloudErrorData
  # @return [Array<TypedErrorInfo>] the list of additional error info parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#21
  def additionalInfo; end

  # @return [Array<TypedErrorInfo>] the list of additional error info parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#21
  def additionalInfo=(_arg0); end

  # @return [String] the error code parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#12
  def code; end

  # @return [String] the error code parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#12
  def code=(_arg0); end

  # @return [String] the error message parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#15
  def message; end

  # @return [String] the error message parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#15
  def message=(_arg0); end

  # @return [String] the error target parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#18
  def target; end

  # @return [String] the error target parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#18
  def target=(_arg0); end

  class << self
    # Deserializes given hash into CloudErrorData object.
    #
    # @param object [Hash] object to deserialize.
    # @return [CloudErrorData] deserialized object.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/cloud_error_data.rb#28
    def deserialize_object(object); end
  end
end

# Class that provides access to authentication token.
#
# source://ms_rest_azure//lib/ms_rest_azure/credentials/cognitive_services_credentials.rb#9
class MsRestAzure::CognitiveServicesCredentials < ::MsRest::ServiceClientCredentials
  # Creates and initialize new instance of the CognitiveServicesCredentials class.
  #
  # @param subscription_key [String] subscription key
  # @return [CognitiveServicesCredentials] a new instance of CognitiveServicesCredentials
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/cognitive_services_credentials.rb#21
  def initialize(subscription_key); end

  # source://ms_rest_azure//lib/ms_rest_azure/credentials/cognitive_services_credentials.rb#27
  def sign_request(request); end

  private

  # @return [String] the subscription key
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/cognitive_services_credentials.rb#14
  def subscription_key; end
end

# source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#5
module MsRestAzure::Common; end

# The Azure::Common::Configurable module provides basic configuration for Azure activities.
#
# source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#7
module MsRestAzure::Common::Configurable
  # @return [MsRestAzure::ActiveDirectoryServiceSettings] Azure active directory service settings.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#21
  def active_directory_settings; end

  # @return [MsRestAzure::ActiveDirectoryServiceSettings] Azure active directory service settings.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#21
  def active_directory_settings=(_arg0); end

  # @return [String] Azure client id.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#12
  def client_id; end

  # @return [String] Azure client id.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#12
  def client_id=(_arg0); end

  # @return [String] Azure secret key.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#15
  def client_secret; end

  # @return [String] Azure secret key.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#15
  def client_secret=(_arg0); end

  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#71
  def config; end

  # Set configuration options using a block.
  #
  # @yield [_self]
  # @yieldparam _self [MsRestAzure::Common::Configurable] the object that the method was called on
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#39
  def configure; end

  # @return [MsRest::ServiceClientCredentials] credentials to authorize HTTP requests made by the service client.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#24
  def credentials; end

  # @return [MsRest::ServiceClientCredentials] credentials to authorize HTTP requests made by the service client.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#24
  def credentials=(_arg0); end

  # Resets the configurable options to provided options or defaults.
  # This will also creates MsRest::TokenCredentials to be used for subsequent Azure Resource Manager clients.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#47
  def reset!(options = T.unsafe(nil)); end

  # @return [String] Azure subscription id.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#18
  def subscription_id; end

  # @return [String] Azure subscription id.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#18
  def subscription_id=(_arg0); end

  # @return [String] Azure tenant id (also known as domain).
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#9
  def tenant_id; end

  # @return [String] Azure tenant id (also known as domain).
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#9
  def tenant_id=(_arg0); end

  private

  # configures configurable options to default values
  #
  # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#80
  def setup_default_options; end

  class << self
    # List of configurable keys for {Azure::Common::Client}.
    #
    # @return [Array] of option keys.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/common/configurable.rb#31
    def keys; end
  end
end

# source://ms_rest_azure//lib/ms_rest_azure/common/default.rb#6
module MsRestAzure::Common::Default
  class << self
    # Default Azure Active Directory Service Settings.
    #
    # @return [MsRestAzure::ActiveDirectoryServiceSettings] Azure Active Directory Service Settings.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/common/default.rb#44
    def active_directory_settings; end

    # Default Azure Client Id.
    #
    # @return [String] Azure Client Id.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/common/default.rb#20
    def client_id; end

    # Default Azure Client Secret.
    #
    # @return [String] Azure Client Secret.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/common/default.rb#28
    def client_secret; end

    # Configuration options.
    #
    # @return [Hash] Configuration options.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/common/default.rb#52
    def options; end

    # Default Azure Subscription Id.
    #
    # @return [String] Azure Subscription Id.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/common/default.rb#36
    def subscription_id; end

    # Default Azure Tenant Id.
    #
    # @return [String] Azure Tenant Id.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/common/default.rb#12
    def tenant_id; end
  end
end

# Class which represents a final state via of Azure long running operation.
#
# source://ms_rest_azure//lib/ms_rest_azure/final_state_via.rb#9
class MsRestAzure::FinalStateVia; end

# source://ms_rest_azure//lib/ms_rest_azure/final_state_via.rb#12
MsRestAzure::FinalStateVia::AZURE_ASYNC_OPERATION = T.let(T.unsafe(nil), Integer)

# source://ms_rest_azure//lib/ms_rest_azure/final_state_via.rb#11
MsRestAzure::FinalStateVia::DEFAULT = T.let(T.unsafe(nil), Integer)

# source://ms_rest_azure//lib/ms_rest_azure/final_state_via.rb#13
MsRestAzure::FinalStateVia::LOCATION = T.let(T.unsafe(nil), Integer)

# source://ms_rest_azure//lib/ms_rest_azure/final_state_via.rb#10
MsRestAzure::FinalStateVia::NONE = T.let(T.unsafe(nil), Integer)

# source://ms_rest_azure//lib/ms_rest_azure/final_state_via.rb#14
MsRestAzure::FinalStateVia::ORIGINAL_URI = T.let(T.unsafe(nil), Integer)

# Class that provides access to authentication token via Managed Service Identity.
#
# source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#9
class MsRestAzure::MSITokenProvider < ::MsRest::TokenProvider
  # Creates and initialize new instance of the MSITokenProvider class.
  # or
  #  msi_id = {'object_id': 'object id of user assigned identity'}
  # or
  #  msi_id = {'msi_rest_id': 'resource id of user assigned identity'}
  # The above key,value pairs are mutually exclusive.
  #
  # @param port [Integer] port number where MSI service is running.
  # @param settings [ActiveDirectoryServiceSettings] active directory setting.
  # @param msi_id [Hash] MSI id for user assigned managed service identity,
  #   msi_id = {'client_id': 'client id of user assigned identity'}
  # @return [MSITokenProvider] a new instance of MSITokenProvider
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#65
  def initialize(port = T.unsafe(nil), settings = T.unsafe(nil), msi_id = T.unsafe(nil)); end

  # Returns the string value which needs to be attached
  # to HTTP request header in order to be authorized.
  #
  # @return [String] authentication headers.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#86
  def get_authentication_header; end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#52
  def token; end

  # @return [Time] the date when the current token expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#46
  def token_expires_on; end

  # @return [String] the type of token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#49
  def token_type; end

  private

  # Retrieves a new authentication token.
  #
  # @return [String] new authentication token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#170
  def acquire_token; end

  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#101
  def acquire_token_from_imds_with_retry; end

  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#97
  def append_header(name, value); end

  # @return [String] client id for user assigned managed identity
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#26
  def client_id; end

  # @return [String] client id for user assigned managed identity
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#26
  def client_id=(_arg0); end

  # @return [Integer] the amount of time we refresh token before it expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#41
  def expiration_threshold; end

  # @return [String] ms_res id for user assigned managed identity
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#32
  def msi_res_id; end

  # @return [String] ms_res id for user assigned managed identity
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#32
  def msi_res_id=(_arg0); end

  # @return [String] object id for user assigned managed identity
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#29
  def object_id; end

  # @return [String] object id for user assigned managed identity
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#29
  def object_id=(_arg0); end

  # @return [Integer] port number where MSI service is running.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#23
  def port; end

  # @return [Integer] port number where MSI service is running.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#23
  def port=(_arg0); end

  # Sets user assigned identity value in request body
  #
  # @param request_body [String] body of the request used to acquire token
  # @param id_type [String] type of id to send 'client_id', 'object_id' or 'msi_res_id'
  # @param id_value [String] id of the user assigned identity
  # @return [String] new request body with the addition of <id_type>=<id_value>.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#208
  def set_msi_id(request_body, id_type, id_value); end

  # @return [MSIActiveDirectoryServiceSettings] settings.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#20
  def settings; end

  # @return [MSIActiveDirectoryServiceSettings] settings.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#20
  def settings=(_arg0); end

  # @return [String] auth token.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#35
  def token=(_arg0); end

  # Checks whether token is about to expire.
  #
  # @return [Bool] True if token is about to expire, false otherwise.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#162
  def token_expired; end

  # @return [Time] the date when the current token expires.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#38
  def token_expires_on=(_arg0); end
end

# source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#16
MsRestAzure::MSITokenProvider::DEFAULT_SCHEME = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#17
MsRestAzure::MSITokenProvider::IMDS_TOKEN_ACQUIRE_URL = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#14
MsRestAzure::MSITokenProvider::REQUEST_BODY_PATTERN = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#13
MsRestAzure::MSITokenProvider::TOKEN_ACQUIRE_URL = T.let(T.unsafe(nil), String)

# source://ms_rest_azure//lib/ms_rest_azure/credentials/msi_token_provider.rb#15
MsRestAzure::MSITokenProvider::USER_ASSIGNED_IDENTITY = T.let(T.unsafe(nil), String)

# Class which represents a state of Azure long running operation.
#
# source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#9
class MsRestAzure::PollingState
  # @return [PollingState] a new instance of PollingState
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#32
  def initialize(azure_response, retry_timeout); end

  # @return [String] the latest value captured from Azure-AsyncOperation header.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#24
  def azure_async_operation_header_link; end

  # @return [String] the latest value captured from Azure-AsyncOperation header.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#24
  def azure_async_operation_header_link=(_arg0); end

  # @return [AzureOperationError] the azure error data.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#21
  def error_data; end

  # @return [AzureOperationError] the azure error data.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#21
  def error_data=(_arg0); end

  # Returns the amount of time in seconds for long running operation polling delay.
  #
  # @return [Integer] Amount of time in seconds for long running operation polling delay.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#74
  def get_delay; end

  # Composes and returns cloud error.
  #
  # @return [AzureOperationError] the cloud error.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#109
  def get_operation_error; end

  # returns the Azure's response.
  #
  # @return [MsRestAzure::AzureOperationResponse] Azure's response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#100
  def get_operation_response; end

  # Returns the provisioning status of the resource
  #
  # @return [String] provisioning status of the resource
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#58
  def get_provisioning_state; end

  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#113
  def get_request(options = T.unsafe(nil)); end

  # @return [String] the latest value captured from Location header.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#27
  def location_header_link; end

  # @return [String] the latest value captured from Location header.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#27
  def location_header_link=(_arg0); end

  # @return [Net::HTTPRequest] the HTTP request.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#12
  def request; end

  # @return [Net::HTTPRequest] the HTTP request.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#12
  def request=(_arg0); end

  # @return the resource
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#15
  def resource; end

  # @return the resource
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#15
  def resource=(_arg0); end

  # @return [Net::HTTPResponse] the HTTP response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#18
  def response; end

  # @return [Net::HTTPResponse] the HTTP response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#18
  def response=(_arg0); end

  # @return [String] status of the long running operation.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#30
  def status; end

  # @return [String] status of the long running operation.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#30
  def status=(_arg0); end

  # Updates the polling state from the fields of given response object.
  #
  # @param response [Net::HTTPResponse] the HTTP response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#87
  def update_response(response); end

  private

  # Returns the value of attribute connection.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#124
  def connection; end

  # Sets the attribute connection
  #
  # @param value the value to set the attribute connection to.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#124
  def connection=(_arg0); end

  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#126
  def create_connection(base_url); end

  # @return [Integer] retry timeout.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#122
  def retry_timeout; end

  # @return [Integer] retry timeout.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/polling_state.rb#122
  def retry_timeout=(_arg0); end
end

# Base module for Azure Ruby serialization and deserialization.
#
# Provides methods to serialize Ruby object into Ruby Hash and
# to deserialize Ruby Hash into Ruby object.
#
# source://ms_rest_azure//lib/ms_rest_azure/serialization.rb#10
module MsRestAzure::Serialization
  include ::MsRest::Serialization

  private

  # Builds serializer
  #
  # source://ms_rest_azure//lib/ms_rest_azure/serialization.rb#18
  def build_serializer; end
end

# Class to handle serialization & deserialization.
#
# source://ms_rest_azure//lib/ms_rest_azure/serialization.rb#25
class MsRestAzure::Serialization::Serialization < ::MsRest::Serialization::Serialization
  # Retrieves model of the model_name
  #
  # @param model_name [String] Name of the model to retrieve.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/serialization.rb#32
  def get_model(model_name); end
end

# Class that provides access to authentication token.
#
# source://ms_rest_azure//lib/ms_rest_azure/credentials/topic_credentials.rb#9
class MsRestAzure::TopicCredentials < ::MsRest::ServiceClientCredentials
  # Creates and initialize new instance of the TopicCredentials class.
  #
  # @param topic_key [String] topic key
  # @return [TopicCredentials] a new instance of TopicCredentials
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/topic_credentials.rb#21
  def initialize(topic_key); end

  # source://ms_rest_azure//lib/ms_rest_azure/credentials/topic_credentials.rb#27
  def sign_request(request); end

  private

  # @return [String] the topic key
  #
  # source://ms_rest_azure//lib/ms_rest_azure/credentials/topic_credentials.rb#14
  def topic_key; end
end

# Class which represents the error type and information.
#
# source://ms_rest_azure//lib/ms_rest_azure/typed_error_info.rb#9
class MsRestAzure::TypedErrorInfo
  # @return [Object] the error info parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/typed_error_info.rb#15
  def info; end

  # @return [Object] the error info parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/typed_error_info.rb#15
  def info=(_arg0); end

  # @return [String] the error type parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/typed_error_info.rb#12
  def type; end

  # @return [String] the error type parsed from the body of the http error response.
  #
  # source://ms_rest_azure//lib/ms_rest_azure/typed_error_info.rb#12
  def type=(_arg0); end

  class << self
    # Deserializes given hash into TypedErrorInfo object.
    #
    # @param object [Hash] object to deserialize.
    # @return [TypedErrorInfo] deserialized object.
    #
    # source://ms_rest_azure//lib/ms_rest_azure/typed_error_info.rb#22
    def deserialize_object(object); end
  end
end

# source://ms_rest_azure//lib/ms_rest_azure/version.rb#6
MsRestAzure::VERSION = T.let(T.unsafe(nil), String)
