# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `octicons` gem.
# Please instead update this file by running `bin/tapioca gem octicons`.


# source://octicons//lib/octicons/version.rb#3
module Octicons; end

# source://octicons//lib/octicons.rb#9
Octicons::OCTICON_SYMBOLS = T.let(T.unsafe(nil), Hash)

# source://octicons//lib/octicons/octicon.rb#4
class Octicons::Octicon
  # @return [Octicon] a new instance of Octicon
  #
  # source://octicons//lib/octicons/octicon.rb#9
  def initialize(symbol, options = T.unsafe(nil)); end

  # Returns the value of attribute height.
  #
  # source://octicons//lib/octicons/octicon.rb#7
  def height; end

  # Returns the value of attribute keywords.
  #
  # source://octicons//lib/octicons/octicon.rb#7
  def keywords; end

  # Returns the value of attribute options.
  #
  # source://octicons//lib/octicons/octicon.rb#7
  def options; end

  # Returns the value of attribute path.
  #
  # source://octicons//lib/octicons/octicon.rb#7
  def path; end

  # Returns the value of attribute symbol.
  #
  # source://octicons//lib/octicons/octicon.rb#7
  def symbol; end

  # Returns an string representing a <svg> tag
  #
  # source://octicons//lib/octicons/octicon.rb#30
  def to_svg; end

  # Returns the value of attribute width.
  #
  # source://octicons//lib/octicons/octicon.rb#7
  def width; end

  private

  # add some accessibility features to svg
  #
  # source://octicons//lib/octicons/octicon.rb#43
  def a11y; end

  # source://octicons//lib/octicons/octicon.rb#84
  def calculate_height(width); end

  # source://octicons//lib/octicons/octicon.rb#80
  def calculate_width(height); end

  # prepare the octicon class
  #
  # source://octicons//lib/octicons/octicon.rb#56
  def classes; end

  # source://octicons//lib/octicons/octicon.rb#103
  def closest_natural_height(natural_heights, height); end

  # source://octicons//lib/octicons/octicon.rb#88
  def get_octicon(symbol, options = T.unsafe(nil)); end

  # source://octicons//lib/octicons/octicon.rb#36
  def html_attributes; end

  # determine the height and width of the octicon based on :size option
  #
  # source://octicons//lib/octicons/octicon.rb#65
  def size; end

  # source://octicons//lib/octicons/octicon.rb#60
  def viewbox; end
end

# source://octicons//lib/octicons/octicon.rb#5
Octicons::Octicon::DEFAULT_HEIGHT = T.let(T.unsafe(nil), Integer)

# source://octicons//lib/octicons/version.rb#4
Octicons::VERSION = T.let(T.unsafe(nil), String)
