# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::Breadcrumbs::Item`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::Breadcrumbs::Item`.


class Primer::Beta::Breadcrumbs::Item
  sig { void }
  def initialize; end
end
