# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::ActionBar::Divider`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::ActionBar::Divider`.


class Primer::Alpha::ActionBar::Divider
  sig { void }
  def initialize; end
end
