# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::ActionBar::Item`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::ActionBar::Item`.


class Primer::Alpha::ActionBar::Item
  sig { params(item_arguments: T::Hash).void }
  def initialize(**item_arguments); end
end
