# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::CheckBoxGroup`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::CheckBoxGroup`.


class Primer::Alpha::CheckBoxGroup
  sig { void }
  def initialize; end
end
