# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::HellipButton`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::HellipButton`.


class Primer::Alpha::HellipButton
  sig { params(inline: T::Boolean, disabled: T::Boolean, system_arguments: T::Hash).void }
  def initialize(inline:, disabled:, **system_arguments); end
end
