# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::HiddenTextExpander`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::HiddenTextExpander`.


class Primer::Alpha::HiddenTextExpander
  sig { params(inline: T::Boolean, button_arguments: T::Hash, system_arguments: T::Hash).void }
  def initialize(inline:, button_arguments:, **system_arguments); end
end
