# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::Image`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::Image`.


class Primer::Alpha::Image
  sig { params(lazy: T::Boolean, system_arguments: T::Hash).void }
  def initialize(lazy:, **system_arguments); end
end
