# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::OcticonSymbols`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::OcticonSymbols`.


class Primer::Alpha::OcticonSymbols
  sig { params(icons: T::Array[]).void }
  def initialize(icons:); end
end
