# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::RadioButtonGroup`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::RadioButtonGroup`.


class Primer::Alpha::RadioButtonGroup
  sig { void }
  def initialize; end
end
