# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::StackItem`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::StackItem`.


class Primer::Alpha::StackItem
  sig { params(tag: Symbol, grow: T::Boolean, system_arguments: T::Hash).void }
  def initialize(tag:, grow:, **system_arguments); end
end
