# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::TabContainer`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::TabContainer`.


class Primer::Alpha::TabContainer
  sig { params(system_arguments: T::Hash).void }
  def initialize(**system_arguments); end
end
