# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::Tooltip`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::Tooltip`.


class Primer::Alpha::Tooltip
  sig { params(direction: Symbol, system_arguments: T::Hash).void }
  def initialize(direction:, **system_arguments); end
end
