# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::ActionList::Divider`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::ActionList::Divider`.


class Primer::Alpha::ActionList::Divider
  sig { params(scheme: Symbol, system_arguments: T::Hash).void }
  def initialize(scheme:, **system_arguments); end
end
