# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::ActionList::FormWrapper`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::ActionList::FormWrapper`.


class Primer::Alpha::ActionList::FormWrapper
  sig { void }
  def initialize; end
end
