# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::ActionList::Heading`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::ActionList::Heading`.


class Primer::Alpha::ActionList::Heading
  sig { params(heading_level: Integer, scheme: Symbol, subtitle: String, system_arguments: T::Hash).void }
  def initialize(heading_level:, scheme:, subtitle:, **system_arguments); end
end
