# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::Overlay::Footer`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::Overlay::Footer`.


class Primer::Alpha::Overlay::Footer
  sig { params(show_divider: T::Boolean, align_content: Symbol, system_arguments: T::Hash).void }
  def initialize(show_divider:, align_content:, **system_arguments); end
end
