# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::NavList::Heading`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::NavList::Heading`.


class Primer::Alpha::NavList::Heading
  sig { params(id: String, heading_level: Integer, system_arguments: T::Hash).void }
  def initialize(id:, heading_level:, **system_arguments); end
end
