# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::ButtonGroup::MenuButton`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::ButtonGroup::MenuButton`.


class Primer::Beta::ButtonGroup::MenuButton
  sig { params(menu_arguments: T::Hash, button_arguments: T::Hash).void }
  def initialize(menu_arguments:, button_arguments:); end
end
