# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::Layout::Main`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::Layout::Main`.


class Primer::Alpha::Layout::Main
  sig { params(width: Symbol, system_arguments: T::Hash).void }
  def initialize(width:, **system_arguments); end
end
