# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Alpha::Layout::Sidebar`.
# Please instead update this file by running `bin/tapioca dsl Primer::Alpha::Layout::Sidebar`.


class Primer::Alpha::Layout::Sidebar
  sig { void }
  def initialize; end
end
