# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::Beta::TimelineItem::Badge`.
# Please instead update this file by running `bin/tapioca dsl Primer::Beta::TimelineItem::Badge`.


class Primer::Beta::TimelineItem::Badge
  sig { void }
  def initialize; end
end
